export const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error occurred',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_LENGTH_INVALID: 'Name must be between 1 and 100 characters',
  NAME_MUST_BE_STRING: 'Name must be a string',
  EMAIL_ALREADY_IN_USE: 'Email already in use',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  EMAIL_MUST_BE_VALID: 'Email must be a valid email address',
  EMAIL_OR_PASSWORD_INCORRECT: 'Email or password is incorrect',
  USER_NOT_FOUND: 'User not found',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_STRING: 'Password must be a string',
  PASSWORD_LENGTH_INVALID: 'Password must be between 6 and 50 characters',
  PASSWORD_NOT_STRONG_ENOUGH: 'Password is not strong enough',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_INVALID: 'Confirm password must be between 6 and 50 characters',
  CONFIRM_PASSWORD_NOT_STRONG_ENOUGH: 'Confirm password is not strong enough',
  PASSWORD_CONFIRMATION_DOES_NOT_MATCH: 'Password confirmation does not match password',
  DATE_OF_BIRTH_MUST_BE_ISO8601: 'Date of birth must be a valid ISO 8601 date',
  LOGIN_SUCCESS: 'Login success',
  REGISTER_SUCCESS: 'Register success',
  LOGOUT_SUCCESS: 'Logout success',
  ACCESS_TOKEN_IS_REQUIRED: 'Authorization header is required',
  AUTHORIZATION_HEADER_INVALID: 'Invalid authorization header',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_INVALID: 'Refresh token is invalid',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  EMAIL_VERIFY_TOKEN_INVALID: 'Email verify token is invalid',
  EMAIL_ALREADY_VERIFIED: 'Email already verified',
  EMAIL_VERIFY_SUCCESS: 'Email verified successfully',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Resend verify email successfully',
  USER_IS_BANNED: 'User is banned',
  FORGOT_PASSWORD_SUCCESS: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_IS_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Forgot password token is invalid',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully',
  GET_ME_SUCCESS: 'Get me successfully',
  UPDATE_ME_SUCCESS: 'Update me successfully',
  USERNAME_ALREADY_IN_USE: 'Username already in use',
  USERNAME_INVALID: 'Username must be 4-15 characters, only letters, numbers and underscores',
  CHANGE_PASSWORD_SUCCESS: 'Change password successfully',
  OLD_PASSWORD_IS_REQUIRED: 'Old password is required',
  OLD_PASSWORD_INCORRECT: 'Old password is incorrect',
  NEW_PASSWORD_IS_REQUIRED: 'New password is required',
  NEW_PASSWORD_MUST_BE_DIFFERENT: 'New password must be different from old password',
  GET_PROFILE_SUCCESS: 'Get profile successfully',
  FOLLOW_SUCCESS: 'Follow successfully',
  UNFOLLOW_SUCCESS: 'Unfollow successfully',
  ALREADY_FOLLOWED: 'Already followed',
  NOT_FOLLOWED: 'Not followed yet',
  FOLLOWED_USER_ID_IS_REQUIRED: 'Followed user id is required',
  FOLLOWED_USER_ID_INVALID: 'Followed user id is invalid',
  FOLLOWED_USER_NOT_FOUND: 'Followed user not found',
  CANNOT_FOLLOW_YOURSELF: 'Cannot follow yourself',
  CREATE_TWEET_SUCCESS: 'Create tweet successfully',
  GET_TWEET_SUCCESS: 'Get tweet successfully',
  GET_TIMELINE_SUCCESS: 'Get timeline successfully',
  TWEET_NOT_FOUND: 'Tweet not found',
  TWEET_TYPE_INVALID: 'Tweet type is invalid',
  TWEET_AUDIENCE_INVALID: 'Tweet audience is invalid',
  TWEET_CONTENT_IS_REQUIRED: 'Tweet content is required for tweet and quote tweet',
  TWEET_CONTENT_MUST_BE_EMPTY: 'Tweet content must be empty for retweet',
  PARENT_ID_IS_REQUIRED: 'Parent id is required for retweet, comment and quote tweet',
  PARENT_ID_MUST_BE_NULL: 'Parent id must be null for tweet',
  PARENT_TWEET_NOT_FOUND: 'Parent tweet not found',
  TWEET_ID_INVALID: 'Tweet id is invalid'
} as const
